---
title: "Logger Comparison"
author: "Stefan Fleck"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    number_sections: true
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(devtools)
library(bench)
library(dplyr)
library(forcats)

```

```{r eval = FALSE}
install_github("daroczig/logger")
install.packages("log4r")
install.packages("futile.logger")
install.packages("logging")
```

```{r}
library(yog)
library(logger)
library(log4r)
library(futile.logger)
```



Setup packages that do not work out-of-the-box
```{r}
logging::addHandler(logging::writeToConsole, logger="logging")

yog::yog$info("an informative message")
logging::loginfo("an informative message")
futile.logger::flog.info("an informative message")

```

# Syntax Examples


# Feature Matrix


# Performance

## Simple Console Logging Call

Log a simple log message (without colors)

```{r, results='hide'}

# log4r does not support logging to the console

# yog uses color output by default, which slows down logging
# yog$set_appenders(AppenderConsole$new(layout = LayoutFormat$new(colors = NULL)))

library(yog)

lg2 <- Logger$new("blubb", appenders = AppenderConsole$new(layout = LayoutFormat$new()), parent = NULL)


shmock <- function() yog$log(100, "test", caller = NULL)

sink("/dev/null")
res <- bench::mark(
  logger = logger::log_info("test"),
  futile.logger = futile.logger::flog.info("test"),
  logging = logging::logerror("test", logger = "logging"),
  yog = yog::yog$info("test"),
  lg2 = lg2$info("test"),
  schock = shmock(),
  check = FALSE
)
sink()

```
```{r}

res %>% 
  select(expression, min, mean, median, mem_alloc) %>% 
  arrange(median) %>% 
  knitr::kable()

res$expression <- fct_reorder(res$expression, res$median)
  
plot(res)

```


# Log a simple log message (with colors)

```{r, results='hide'}
yog$set_appenders(AppenderConsole$new())
log_layout(layout_glue_colors)

sink("/dev/null")
res <- bench::mark(
  logger = logger::log_fatal("test"),
  yog = yog::yog$info("test"),
  check = FALSE
)
sink()

```

```{r}

res %>% 
  select(expression, min, mean, median, mem_alloc) %>% 
  arrange(median) %>% 
  knitr::kable()

res$expression <- fct_reorder(res$expression, res$median)
  
plot(res)

```


# Log a suppressed message

```{r}
yog$set_threshold("info")

res <- bench::mark(
  logger = logger::log_debug("test"),
  futile.logger = futile.logger::flog.debug("test"),
  logging = logging::logdebug("test", logger = "logging"),
  yog = yog::yog$debug("test"),
  check = FALSE
)

```

```{r}
plot(res)

```

